/** Modern icons using Lucide React - Latest version */

import {
  Home,
  MessageSquare,
  Clock,
  Car,
  Users,
  Settings,
  ChevronDown,
  HelpCircle,
  LogOut,
  Building2,
  Sparkles,
  Zap,
} from "lucide-react";

interface IconProps {
  className?: string;
  size?: number;
}

export const HomeIcon = ({ className = "", size = 24 }: IconProps) => (
  <Home className={className} size={size} />
);

export const MessageSquareIcon = ({ className = "", size = 24 }: IconProps) => (
  <MessageSquare className={className} size={size} />
);

export const ClockIcon = ({ className = "", size = 24 }: IconProps) => (
  <Clock className={className} size={size} />
);

export const CarIcon = ({ className = "", size = 24 }: IconProps) => (
  <Car className={className} size={size} />
);

export const UsersIcon = ({ className = "", size = 24 }: IconProps) => (
  <Users className={className} size={size} />
);

export const SettingsIcon = ({ className = "", size = 24 }: IconProps) => (
  <Settings className={className} size={size} />
);

export const ChevronDownIcon = ({ className = "", size = 24 }: IconProps) => (
  <ChevronDown className={className} size={size} />
);

export const HelpCircleIcon = ({ className = "", size = 24 }: IconProps) => (
  <HelpCircle className={className} size={size} />
);

export const LogOutIcon = ({ className = "", size = 24 }: IconProps) => (
  <LogOut className={className} size={size} />
);

export const BuildingIcon = ({ className = "", size = 24 }: IconProps) => (
  <Building2 className={className} size={size} />
);

export const SparklesIcon = ({ className = "", size = 24 }: IconProps) => (
  <Sparkles className={className} size={size} />
);

export const ZapIcon = ({ className = "", size = 24 }: IconProps) => (
  <Zap className={className} size={size} />
);

// Additional modern icons
export {
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  Plus,
  Search,
  Filter,
  Download,
  Upload,
  Edit,
  Trash2,
  Save,
  FileText,
  Image as ImageIcon,
  Video,
  Link,
  Copy,
  Share2,
  Bell,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock as ClockIcon,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Activity,
  Target,
  Award,
  Trophy,
  Gift,
  ShoppingCart,
  CreditCard,
  Wallet,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Bitcoin,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Menu,
  X,
  MoreVertical,
  MoreHorizontal,
  Grid,
  List,
  Layout,
  Sidebar as SidebarIcon,
  Maximize2,
  Minimize2,
  RefreshCw,
  RotateCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Move,
  Crop,
  Scissors,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List as ListIcon,
  ListOrdered,
  Quote,
  Code,
  Code2,
  Terminal,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Wifi,
  WifiOff,
  Signal,
  Radio,
  Bluetooth,
  BluetoothConnected,
  BluetoothSearching,
  BluetoothOff,
  Headphones,
  Speaker,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Video as VideoIcon,
  VideoOff,
  Camera,
  CameraOff,
  Image as ImageIcon2,
  Film,
  Music,
  Music2,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Volume1,
  Volume,
  Maximize,
  Minimize,
  X as XIcon,
  Check,
  X as XIcon2,
  Plus as PlusIcon,
  Minus,
  Divide,
  Percent,
  Hash,
  AtSign,
  DollarSign as DollarIcon,
  Euro as EuroIcon,
  PoundSterling as PoundIcon,
  Yen as YenIcon,
  Bitcoin as BitcoinIcon,
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon,
  ShoppingCart as ShoppingCartIcon,
  Gift as GiftIcon,
  Trophy as TrophyIcon,
  Award as AwardIcon,
  Target as TargetIcon,
  Activity as ActivityIcon,
  PieChart as PieChartIcon,
  BarChart3 as BarChart3Icon,
  TrendingDown as TrendingDownIcon,
  TrendingUp as TrendingUpIcon,
  Calendar as CalendarIcon,
  MapPin as MapPinIcon,
  Phone as PhoneIcon,
  Mail as MailIcon,
  Key as KeyIcon,
  Unlock as UnlockIcon,
  Lock as LockIcon,
  EyeOff as EyeOffIcon,
  Eye as EyeIcon,
  ThumbsUp as ThumbsUpIcon,
  Heart as HeartIcon,
  Star as StarIcon,
  Bell as BellIcon,
  Share2 as Share2Icon,
  Copy as CopyIcon,
  Link as LinkIcon,
  Video as VideoIcon2,
  ImageIcon as ImageIcon3,
  FileText as FileTextIcon,
  Save as SaveIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Filter as FilterIcon,
  Search as SearchIcon,
  Plus as PlusIcon2,
  Trash2 as Trash2Icon,
  Edit as EditIcon,
  X as XIcon3,
  Menu as MenuIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  ChevronDown as ChevronDownIcon2,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Layout as LayoutIcon,
  List as ListIcon2,
  Grid as GridIcon,
  SidebarIcon as SidebarIcon2,
  Minimize2 as Minimize2Icon,
  Maximize2 as Maximize2Icon,
  RotateCcw as RotateCcwIcon,
  RotateCw as RotateCwIcon,
  RefreshCw as RefreshCwIcon,
  ZoomOut as ZoomOutIcon,
  ZoomIn as ZoomInIcon,
  Move as MoveIcon,
  Crop as CropIcon,
  Scissors as ScissorsIcon,
  Type as TypeIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline as UnderlineIcon,
  Strikethrough as StrikethroughIcon,
  AlignLeft as AlignLeftIcon,
  AlignCenter as AlignCenterIcon,
  AlignRight as AlignRightIcon,
  AlignJustify as AlignJustifyIcon,
  ListOrdered as ListOrderedIcon,
  Quote as QuoteIcon,
  Code as CodeIcon,
  Code2 as Code2Icon,
  Terminal as TerminalIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cloud as CloudIcon,
  CloudUpload as CloudUploadIcon,
  CloudDownload as CloudDownloadIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Signal as SignalIcon,
  Radio as RadioIcon,
  Bluetooth as BluetoothIcon,
  BluetoothConnected as BluetoothConnectedIcon,
  BluetoothSearching as BluetoothSearchingIcon,
  BluetoothOff as BluetoothOffIcon,
  Headphones as HeadphonesIcon,
  Speaker as SpeakerIcon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  VideoOff as VideoOffIcon,
  Camera as CameraIcon,
  CameraOff as CameraOffIcon,
  Film as FilmIcon,
  Music as MusicIcon,
  Music2 as Music2Icon,
  Play as PlayIcon,
  Pause as PauseIcon,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  Repeat as RepeatIcon,
  Shuffle as ShuffleIcon,
  Volume1 as Volume1Icon,
  Volume as VolumeIcon,
  Maximize as MaximizeIcon,
  Minimize as MinimizeIcon,
  Check as CheckIcon,
  Minus as MinusIcon,
  Divide as DivideIcon,
  Percent as PercentIcon,
  Hash as HashIcon,
  AtSign as AtSignIcon,
} from "lucide-react";

